import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DiagnosticWizard } from "@/components/DiagnosticWizard";
import { ObjectiveSelector } from "@/components/ObjectiveSelector";
import { PresenceComparison } from "@/components/PresenceComparison";
import { brand, faqs, insights, processSteps, projects, services, whatsappUrl } from "@/content/site";

type Props = { params: Promise<{ slug?: string[] }> };
const valid = new Set(["", "servicos", "projetos", "processo", "diagnostico", "contato", "insights", "politica-de-privacidade", "politica-de-cookies", "termos-de-uso", ...services.map(s => `servicos/${s.slug}`), ...projects.map(p => `projetos/${p.slug}`)]);

export async function generateStaticParams() {
  return [...valid].map(path => ({ slug: path ? path.split("/") : undefined }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const path = (await params).slug?.join("/") || "";
  const service = services.find(s => `servicos/${s.slug}` === path); const project = projects.find(p => `projetos/${p.slug}` === path);
  const title = service?.title || project?.name || ({ servicos: "Serviços", projetos: "Projetos", processo: "Processo", diagnostico: "Diagnóstico gratuito", contato: "Contato", insights: "Insights", "politica-de-privacidade": "Política de Privacidade", "politica-de-cookies": "Política de Cookies", "termos-de-uso": "Termos de Uso" } as Record<string,string>)[path];
  return { title, description: service?.summary || (project ? `${project.name}: ${project.category}. Conheça a atuação confirmada da Dreh Work.` : undefined), alternates: { canonical: `/${path}` } };
}

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="kicker"><span aria-hidden>+</span> {children}</p>; }
function CTA({ context = "meu projeto" }: { context?: string }) { return <section className="cta-band"><div className="shell"><Eyebrow>Próximo movimento</Eyebrow><h2>O que sua presença digital precisa provar?</h2><p>Receba uma análise inicial sobre clareza, confiança, descoberta e oportunidades.</p><div className="button-row"><Link className="button light" href="/diagnostico">Solicitar diagnóstico gratuito</Link><a className="text-link light" href={whatsappUrl(context)} target="_blank" rel="noreferrer">Conversar no WhatsApp</a></div></div></section>; }
function ProjectCard({ project, index }: { project: typeof projects[number]; index: number }) { return <article className="project-card"><div className="media-fallback" role="img" aria-label={project.media[0].alt}><span>{String(index + 1).padStart(2,"0")}</span><b>MÍDIA<br/>PENDENTE</b><small>{project.name}</small></div><div className="project-copy"><p className="kicker">{project.category}</p><h3>{project.name}</h3><p>{project.createdByDrehWork ? "Projeto criado e desenvolvido pela Dreh Work." : "Atuação recorrente em manutenção, personalização e evolução da experiência."}</p><Link className="text-link" href={`/projetos/${project.slug}`}>Ver estudo de caso</Link></div></article>; }

function Home() { return <>
  <section className="hero"><div className="hero-grid" aria-hidden /><div className="shell hero-inner"><div><Eyebrow>Sites estratégicos / Presença digital</Eyebrow><h1>Sua empresa pode ser excelente. <em>A presença digital precisa demonstrar isso.</em></h1><p className="lead">A Dreh Work cria sites profissionais para empresas que precisam transmitir confiança, explicar melhor o que fazem e transformar atenção em oportunidades.</p><div className="button-row"><Link className="button primary" href="/diagnostico">Solicitar diagnóstico gratuito</Link><Link className="button ghost" href="/projetos">Ver projetos</Link></div><p className="trust-line">Contrato · Nota fiscal · Atendimento remoto em todo o Brasil</p></div><aside className="signal-panel"><div className="signal-head"><span>SINAL / PRESENÇA</span><i>ATIVO</i></div><div className="signal-number">01</div><p>Clareza para ser compreendida.<br/>Estrutura para ser encontrada.<br/>Experiência para gerar ação.</p><div className="signal-axis"><span>NEGÓCIO</span><span>PERCEPÇÃO</span><span>RESULTADO</span></div></aside></div></section>
  <section className="section shell split"><div><Eyebrow>O problema não é só não ter um site</Eyebrow><h2>Qualidade real não basta quando ela não é percebida.</h2></div><div className="prose"><p>Uma empresa pode prestar um excelente serviço e ainda perder oportunidades quando o cliente pesquisa, encontra informações dispersas ou não entende por que deveria confiar.</p><ul className="issue-list"><li>Dependência do Instagram</li><li>Indicações sem contexto</li><li>Concorrentes mais bem apresentados</li><li>Próximo passo pouco claro</li></ul></div></section>
  <section className="section section-dark"><div className="shell"><Eyebrow>Demonstração</Eyebrow><div className="section-heading"><h2>Estar na internet não é o mesmo que ter presença.</h2><p>Alterne os estados para comparar como organização, hierarquia e ação mudam a percepção.</p></div><PresenceComparison /></div></section>
  <section className="section shell"><Eyebrow>Capacidades</Eyebrow><div className="section-heading"><h2>Um sistema digital, não uma página isolada.</h2><Link className="text-link" href="/servicos">Ver todos os serviços</Link></div><div className="service-grid">{services.slice(0,4).map((s,i) => <Link className="service-card" href={`/servicos/${s.slug}`} key={s.slug}><span>0{i+1}</span><p className="kicker">{s.eyebrow}</p><h3>{s.title}</h3><p>{s.summary}</p><b aria-hidden>↗</b></Link>)}</div></section>
  <section className="section projects-section"><div className="shell"><Eyebrow>Projetos reais</Eyebrow><div className="section-heading"><h2>Competência demonstrada por trabalho publicado.</h2><Link className="text-link" href="/projetos">Explorar portfólio</Link></div><div className="projects-list">{projects.slice(0,3).map((p,i) => <ProjectCard key={p.slug} project={p} index={i}/>)}</div></div></section>
  <section className="section shell"><Eyebrow>Método Dreh Work</Eyebrow><div className="section-heading"><h2>O layout entra depois que a direção está clara.</h2><Link className="text-link" href="/processo">Conhecer o processo</Link></div><ol className="process-line">{processSteps.map((s,i) => <li key={s}><span>{String(i+1).padStart(2,"0")}</span>{s}</li>)}</ol></section>
  <section className="section section-blue"><div className="shell split"><div><Eyebrow>Pesquisa e inteligência artificial</Eyebrow><h2>Informação organizada é parte da presença digital.</h2></div><div className="prose"><p>Um site bem estruturado ajuda mecanismos modernos de pesquisa e inteligência artificial a interpretar quem é a empresa, o que oferece, onde atua e como pode ser contatada.</p><p>Essa preparação melhora a base de descoberta — sem prometer ranking, citação ou resultado automático.</p></div></div></section>
  <section className="section shell"><Eyebrow>Direção personalizada</Eyebrow><div className="section-heading"><h2>O que sua empresa precisa resolver agora?</h2><p>Escolha uma situação para ver o caminho mais relevante.</p></div><ObjectiveSelector /></section>
  <section className="section section-light"><div className="shell"><Eyebrow>Confiança pela estrutura</Eyebrow><div className="proof-grid">{["Contrato e nota fiscal", "Atendimento direto", "Processo estruturado", "Publicação e verificação", "Suporte e evolução", "Todo o Brasil, remotamente"].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
  <section className="section shell"><Eyebrow>Perguntas frequentes</Eyebrow><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden>+</span></summary><p>{a}</p></details>)}</div></section><CTA />
  </>; }

function ServicesPage() { return <><section className="page-hero shell"><Eyebrow>Serviços</Eyebrow><h1>Sites são o centro. Estratégia, descoberta e evolução completam o sistema.</h1><p className="lead">Cada serviço parte do problema do negócio e da ação que a experiência precisa gerar.</p></section><section className="section shell"><div className="service-grid wide">{services.map((s,i)=><Link className="service-card" href={`/servicos/${s.slug}`} key={s.slug}><span>{String(i+1).padStart(2,"0")}</span><p className="kicker">{s.eyebrow}</p><h2>{s.title}</h2><p>{s.summary}</p><b aria-hidden>↗</b></Link>)}</div></section><CTA /></>; }
function ServicePage({ service }: { service: typeof services[number] }) { const schema={"@context":"https://schema.org","@type":"Service",name:service.title,provider:{"@type":"Organization",name:"Dreh Work"},areaServed:"BR",description:service.summary}; return <><section className="page-hero shell"><Eyebrow>{service.eyebrow}</Eyebrow><h1>{service.title}</h1><p className="lead">{service.summary}</p><div className="button-row"><Link className="button primary" href={`/diagnostico?objetivo=${encodeURIComponent(service.title)}`}>Solicitar diagnóstico</Link><Link className="button ghost" href="/projetos">Ver projetos</Link></div></section><section className="section section-dark"><div className="shell split"><div><Eyebrow>Escopo possível</Eyebrow><h2>Uma solução organizada ao redor do resultado.</h2></div><ul className="large-list">{service.items.map(x=><li key={x}>{x}</li>)}</ul></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><CTA context={service.title}/></>; }
function ProjectsPage() { return <><section className="page-hero shell"><Eyebrow>Projetos</Eyebrow><h1>Trabalho real, escopo confirmado e espaço pronto para as evidências visuais.</h1><p className="lead">As mídias serão inseridas posteriormente. Nenhuma interface fictícia foi atribuída aos projetos.</p></section><section className="section projects-section"><div className="shell projects-list">{projects.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section><CTA /></>; }
function ProjectPage({ project }: { project: typeof projects[number] }) { const schema={"@context":"https://schema.org","@type":"CreativeWork",name:project.name,url:project.url,creator:project.createdByDrehWork?{"@type":"Organization",name:"Dreh Work"}:undefined}; return <><section className="page-hero project-hero shell"><div><Eyebrow>{project.category}</Eyebrow><h1>{project.name}</h1><p className="lead">{project.createdByDrehWork ? "Projeto integralmente criado e desenvolvido pela Dreh Work." : "Atuação contínua em manutenção, personalização, correções e evolução da experiência Shopify."}</p><a className="button primary" href={project.url} target="_blank" rel="noreferrer">Visitar projeto</a></div><div className="media-fallback large" role="img" aria-label={project.media[0].alt}><b>MÍDIA<br/>PENDENTE</b><small>Substituição por dados do projeto</small></div></section><section className="section shell case-grid"><div><Eyebrow>Atuação confirmada</Eyebrow><h2>Entregas</h2><ul className="large-list">{project.scope.map(x=><li key={x}>{x}</li>)}</ul></div><aside><p className="kicker">Estudo de caso</p><h3>Conteúdo detalhado em preparação.</h3><p>Contexto, desafio, estratégia, decisões, experiências desktop e mobile e resultados técnicos serão publicados somente após validação factual e inclusão das mídias.</p></aside></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><CTA context={`um projeto como ${project.name}`}/></>; }
function ProcessPage(){return <><section className="page-hero shell"><Eyebrow>Processo</Eyebrow><h1>Antes da interface, direção. Antes da publicação, validação.</h1><p className="lead">O método organiza negócio, público, conteúdo, experiência e tecnologia em uma sequência clara.</p></section><section className="section shell"><ol className="process-cards">{processSteps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><h2>{s}</h2><p>{["Entendimento da empresa, objetivo, público e situação atual.","Definição de prioridades, mensagens, conversões e diferenciais.","Organização de páginas, conteúdo, navegação e fluxos.","Hierarquia, identidade, componentes e comportamento visual.","Construção com foco em desempenho, responsividade e manutenção.","Configuração dos canais e recursos previstos no escopo.","Testes técnicos, de conteúdo, acessibilidade e funcionamento.","Disponibilização no ambiente final após aprovação.","Validação do domínio, formulários, indexação e eventos.","Suporte, manutenção e melhorias futuras."][i]}</p></li>)}</ol></section><CTA/></>}
function ContactPage(){return <><section className="page-hero shell"><Eyebrow>Contato</Eyebrow><h1>Vamos entender o que sua presença digital precisa resolver.</h1><p className="lead">Atendimento direto, remoto e profissional para empresas em todo o Brasil.</p></section><section className="section shell contact-grid"><a href={whatsappUrl("minha presença digital")} target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>{brand.whatsapp}</strong><small>{brand.hours}</small></a><a href={`mailto:${brand.email}`}><span>E-mail</span><strong>{brand.email}</strong><small>Para propostas e informações</small></a><a href="https://instagram.com/dreh.work" target="_blank" rel="noreferrer"><span>Instagram</span><strong>{brand.instagram}</strong><small>Conteúdo e bastidores</small></a></section><CTA/></>}
function InsightsPage(){return <><section className="page-hero shell"><Eyebrow>Insights</Eyebrow><h1>Conteúdo para decisões digitais mais claras.</h1><p className="lead">Esta área reunirá análises sobre sites, confiança, descoberta, conversão e evolução digital.</p></section><section className="section shell empty-state"><span>{String(insights.length).padStart(2,"0")}</span><h2>Nenhum artigo publicado ainda.</h2><p>Novos conteúdos aparecerão aqui somente quando estiverem completos e revisados. Rascunhos não fazem parte do site público.</p></section><CTA/></>}
function LegalPage({kind}:{kind:string}) { const copy:Record<string,[string,string[]]>={"politica-de-privacidade":["Política de Privacidade",["Esta versão informativa descreve a preparação do site para tratamento responsável de dados.","O diagnóstico em modo de revisão mantém respostas somente no navegador e não realiza envio real.","Quando integrações forem ativadas, esta política deverá ser revisada para informar finalidade, base legal, retenção, fornecedores e direitos aplicáveis."]],"politica-de-cookies":["Política de Cookies",["Nesta versão não há ferramentas externas de analytics ou publicidade ativas.","O navegador é usado apenas para preferências locais, como progresso do diagnóstico, objetivo selecionado e exibição da abertura inicial.","Cookies e scripts não essenciais deverão respeitar consentimento quando forem ativados."]],"termos-de-uso":["Termos de Uso",["O conteúdo deste site apresenta os serviços e projetos confirmados da Dreh Work.","O diagnóstico gratuito é uma análise inicial e não representa auditoria completa ou garantia de resultados.","Condições comerciais definitivas são formalizadas em proposta e contrato."]]}; const [title,paras]=copy[kind]; return <section className="page-hero legal shell"><Eyebrow>Conteúdo sujeito a revisão antes da publicação definitiva</Eyebrow><h1>{title}</h1>{paras.map(p=><p key={p}>{p}</p>)}<p className="review-note">Texto informativo inicial. Não representa validação jurídica.</p></section> }

export default async function Page({params}:Props){const path=(await params).slug?.join("/")||""; if(!valid.has(path))notFound(); if(!path)return <Home/>; if(path==="servicos")return <ServicesPage/>; if(path==="projetos")return <ProjectsPage/>; if(path==="processo")return <ProcessPage/>; if(path==="diagnostico")return <><section className="page-hero shell compact"><Eyebrow>Diagnóstico gratuito</Eyebrow><h1>Uma análise inicial para organizar o próximo passo.</h1><p className="lead">O fluxo abaixo funciona em modo seguro de revisão. Nenhuma resposta é enviada nesta versão.</p></section><section className="section shell"><DiagnosticWizard/></section></>; if(path==="contato")return <ContactPage/>; if(path==="insights")return <InsightsPage/>; const service=services.find(s=>`servicos/${s.slug}`===path); if(service)return <ServicePage service={service}/>; const project=projects.find(p=>`projetos/${p.slug}`===path); if(project)return <ProjectPage project={project}/>; if(path.startsWith("politica")||path==="termos-de-uso")return <LegalPage kind={path}/>; notFound();}
